apiVersion: v1
kind: Namespace
metadata:
  name: opsera-friday-app-0eda8-dev
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: friday-app-0eda8
    opsera.io/env: dev
