apiVersion: v1
kind: ServiceAccount
metadata:
  name: friday-app-0eda8
  namespace: opsera-friday-app-0eda8-dev
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: friday-app-0eda8
