apiVersion: v1
kind: Service
metadata:
  name: friday-app-0eda8
  namespace: opsera-friday-app-0eda8-dev
spec:
  selector:
    app: friday-app-0eda8
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
