apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: friday-app-0eda8
  namespace: opsera-friday-app-0eda8-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: friday-app-0eda8.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: friday-app-0eda8
                port:
                  number: 80
